### ISSUE TITLE
Calculation problem in the Stake Calculator

### ISSUE THREAD

**Issue by JB395** [qtumproject/qtuminfo-ui#6]
There is a math error in the stake calculator for expected times less than one day. For example, if the expected time is exactly one day, the Average Blocks per Year should be 365, but is displayed as 258.61:

![stake calculator](https://user-images.githubusercontent.com/29760787/44861044-b12c6e00-ac45-11e8-999d-b5b1ec38d912.jpg)

This math error shows up in some other stake calculations, and I believe the error ratio of 24/34 comes from this typo on line 101 of stake-calculator.vue:

![typo line 101 of stake-calculator vue](https://user-images.githubusercontent.com/29760787/44861140-eb960b00-ac45-11e8-9355-689f02e8f937.jpg)

**Comment by JB395** [comment]
> less

greater

**Comment by JB395** [comment]
The error occurs for expected times greater than one day.

**Comment by xuanyan0x7c7** [comment]
Thanks for reporting, fixed in https://github.com/qtumproject/qtuminfo-ui/commit/839cf72d5139769d26326fd170921ec156268c49
