### ISSUE TITLE
Rich List Shows Negative Percents

### ISSUE THREAD

**Issue by JB395** [qtumproject/qtuminfo-ui#7]
User Rosen reported the rich list shows negative percentages at the very bottom.

https://qtum.info/misc/rich-list?page=1670

![screenhunter_1340 oct 19 15 21](https://user-images.githubusercontent.com/29760787/47239761-36194580-d3b4-11e8-8eab-39003f65efeb.jpg)

**Comment by xuanyan0x7c7** [comment]
Related issue [https://github.com/qtumproject/qtuminfo/issues/7](url)

**Comment by JB395** [comment]
Why is this closed? Still an issue:

![screenhunter 1686](https://user-images.githubusercontent.com/29760787/47250500-156ee100-d3f0-11e8-801f-f2d1efba495a.jpg)

I think that as addresses above update this may push these bottom addresses to negative numbers.

**Comment by xuanyan0x7c7** [comment]
Please discuss this issue in qtuminfo repo
